apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.network/pulseone-backend-default: "true"
    io.kompose.service: appointments-service
  name: appointments-service
spec:
  containers:
    - env:
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://appointments-postgres-db:5435/appointmentsdb
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
      image: appointments-service
      name: appointments-service
      ports:
        - containerPort: 8083
          hostPort: 8083
          protocol: TCP
      resources:
        limits:
          memory: "268435456"
  restartPolicy: OnFailure
status: {}
