apiVersion: v1
kind: Service
metadata:
  name: appointments-service
spec:
  type: ClusterIP
  selector:
    io.kompose.service: appointments-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083