apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  initContainers:
    - name: wait-for-postgres
      image: busybox
      command: ['sh', '-c', 'until nc -z auth-postgres-db 5433; do echo waiting for postgres; sleep 2; done;']
  containers:
    - env:
        - name: POSTGRES_DSN
          value: user=postgres password=postgres host=auth-postgres-db port=5433 dbname=authdb sslmode=disable
        - name: JWT_SECRET
          value: dev_a_super_long_and_complex_secret_key
      image: auth-service
      name: auth-service
      resources:
        limits:
          memory: "134217728"
  restartPolicy: OnFailure
