// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/user_events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User registration event message
type UserRegistrationEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique user identifier
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// User email address
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// User role (PATIENT, DOCTOR, PHARMACIST, etc.)
	Role string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	// Optional user first name
	FirstName string `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Optional user last name
	LastName string `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Event timestamp (Unix timestamp in seconds)
	Timestamp int64 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// user phone number
	PhoneNumber string `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// Event type identifier
	EventType     string `protobuf:"bytes,8,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegistrationEvent) Reset() {
	*x = UserRegistrationEvent{}
	mi := &file_proto_user_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegistrationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegistrationEvent) ProtoMessage() {}

func (x *UserRegistrationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegistrationEvent.ProtoReflect.Descriptor instead.
func (*UserRegistrationEvent) Descriptor() ([]byte, []int) {
	return file_proto_user_events_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegistrationEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRegistrationEvent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRegistrationEvent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserRegistrationEvent) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserRegistrationEvent) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserRegistrationEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *UserRegistrationEvent) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserRegistrationEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

// Response message for user registration events
type UserRegistrationEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the event was processed successfully
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Optional message with details
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Error code if processing failed
	ErrorCode     string `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegistrationEventResponse) Reset() {
	*x = UserRegistrationEventResponse{}
	mi := &file_proto_user_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegistrationEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegistrationEventResponse) ProtoMessage() {}

func (x *UserRegistrationEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegistrationEventResponse.ProtoReflect.Descriptor instead.
func (*UserRegistrationEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_events_proto_rawDescGZIP(), []int{1}
}

func (x *UserRegistrationEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserRegistrationEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserRegistrationEventResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

var File_proto_user_events_proto protoreflect.FileDescriptor

const file_proto_user_events_proto_rawDesc = "" +
	"\n" +
	"\x17proto/user_events.proto\x12\tevents.v1\"\xf6\x01\n" +
	"\x15UserRegistrationEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12!\n" +
	"\fphone_number\x18\a \x01(\tR\vphoneNumber\x12\x1d\n" +
	"\n" +
	"event_type\x18\b \x01(\tR\teventType\"r\n" +
	"\x1dUserRegistrationEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCodeB\x1dZ\x1bauth-service/internal/protob\x06proto3"

var (
	file_proto_user_events_proto_rawDescOnce sync.Once
	file_proto_user_events_proto_rawDescData []byte
)

func file_proto_user_events_proto_rawDescGZIP() []byte {
	file_proto_user_events_proto_rawDescOnce.Do(func() {
		file_proto_user_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_events_proto_rawDesc), len(file_proto_user_events_proto_rawDesc)))
	})
	return file_proto_user_events_proto_rawDescData
}

var file_proto_user_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_user_events_proto_goTypes = []any{
	(*UserRegistrationEvent)(nil),         // 0: events.v1.UserRegistrationEvent
	(*UserRegistrationEventResponse)(nil), // 1: events.v1.UserRegistrationEventResponse
}
var file_proto_user_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_events_proto_init() }
func file_proto_user_events_proto_init() {
	if File_proto_user_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_events_proto_rawDesc), len(file_proto_user_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_user_events_proto_goTypes,
		DependencyIndexes: file_proto_user_events_proto_depIdxs,
		MessageInfos:      file_proto_user_events_proto_msgTypes,
	}.Build()
	File_proto_user_events_proto = out.File
	file_proto_user_events_proto_goTypes = nil
	file_proto_user_events_proto_depIdxs = nil
}
