// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.25.0
// source: proto/user_events.proto

package proto

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User registration event message
type UserRegistrationEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique user identifier
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// User email address
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// User role (PATIENT, DOCTOR, PHARMACIST, etc.)
	Role string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	// Optional user first name
	FirstName string `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Optional user last name
	LastName string `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Event timestamp (Unix timestamp in seconds)
	Timestamp int64 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// user phone number
	PhoneNumber string `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// Event type identifier
	EventType string `protobuf:"bytes,8,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Optional clinic information (for CLINIC_ADMIN users)
	ClinicData    *ClinicData `protobuf:"bytes,9,opt,name=clinic_data,json=clinicData,proto3" json:"clinic_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegistrationEvent) Reset() {
	*x = UserRegistrationEvent{}
	mi := &file_proto_user_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegistrationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegistrationEvent) ProtoMessage() {}

func (x *UserRegistrationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegistrationEvent.ProtoReflect.Descriptor instead.
func (*UserRegistrationEvent) Descriptor() ([]byte, []int) {
	return file_proto_user_events_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegistrationEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRegistrationEvent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRegistrationEvent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserRegistrationEvent) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserRegistrationEvent) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserRegistrationEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *UserRegistrationEvent) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserRegistrationEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *UserRegistrationEvent) GetClinicData() *ClinicData {
	if x != nil {
		return x.ClinicData
	}
	return nil
}

// Clinic data for clinic admin registration
type ClinicData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Clinic ID from profile service (for updates)
	ClinicId int64 `protobuf:"varint,1,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	// Clinic name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Physical address
	PhysicalAddress string `protobuf:"bytes,3,opt,name=physical_address,json=physicalAddress,proto3" json:"physical_address,omitempty"`
	// Contact phone
	ContactPhone string `protobuf:"bytes,4,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	// Operating hours
	OperatingHours string `protobuf:"bytes,5,opt,name=operating_hours,json=operatingHours,proto3" json:"operating_hours,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClinicData) Reset() {
	*x = ClinicData{}
	mi := &file_proto_user_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClinicData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClinicData) ProtoMessage() {}

func (x *ClinicData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClinicData.ProtoReflect.Descriptor instead.
func (*ClinicData) Descriptor() ([]byte, []int) {
	return file_proto_user_events_proto_rawDescGZIP(), []int{1}
}

func (x *ClinicData) GetClinicId() int64 {
	if x != nil {
		return x.ClinicId
	}
	return 0
}

func (x *ClinicData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClinicData) GetPhysicalAddress() string {
	if x != nil {
		return x.PhysicalAddress
	}
	return ""
}

func (x *ClinicData) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *ClinicData) GetOperatingHours() string {
	if x != nil {
		return x.OperatingHours
	}
	return ""
}

// Clinic update event message
type ClinicUpdateEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Profile service clinic ID
	ClinicId int64 `protobuf:"varint,1,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	// Updated clinic name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Updated address
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// Updated contact phone
	ContactPhone string `protobuf:"bytes,4,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	// Updated operating hours
	OperatingHours string `protobuf:"bytes,5,opt,name=operating_hours,json=operatingHours,proto3" json:"operating_hours,omitempty"`
	// Whether clinic is active
	IsActive bool `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// Event timestamp
	Timestamp int64 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Event type identifier
	EventType     string `protobuf:"bytes,8,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClinicUpdateEvent) Reset() {
	*x = ClinicUpdateEvent{}
	mi := &file_proto_user_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClinicUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClinicUpdateEvent) ProtoMessage() {}

func (x *ClinicUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClinicUpdateEvent.ProtoReflect.Descriptor instead.
func (*ClinicUpdateEvent) Descriptor() ([]byte, []int) {
	return file_proto_user_events_proto_rawDescGZIP(), []int{2}
}

func (x *ClinicUpdateEvent) GetClinicId() int64 {
	if x != nil {
		return x.ClinicId
	}
	return 0
}

func (x *ClinicUpdateEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClinicUpdateEvent) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClinicUpdateEvent) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *ClinicUpdateEvent) GetOperatingHours() string {
	if x != nil {
		return x.OperatingHours
	}
	return ""
}

func (x *ClinicUpdateEvent) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ClinicUpdateEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClinicUpdateEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

var File_proto_user_events_proto protoreflect.FileDescriptor

var (
	file_proto_user_events_proto_rawDescOnce sync.Once
	file_proto_user_events_proto_rawDescData []byte
)

func file_proto_user_events_proto_rawDescGZIP() []byte {
	file_proto_user_events_proto_rawDescOnce.Do(func() {
		file_proto_user_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_user_events_proto_rawDesc)
	})
	return file_proto_user_events_proto_rawDescData
}

var file_proto_user_events_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_user_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
	file_proto_user_events_proto_goTypes  = []any{
		(*UserRegistrationEvent)(nil), // 0: events.v1.UserRegistrationEvent
		(*ClinicData)(nil),            // 1: events.v1.ClinicData
		(*ClinicUpdateEvent)(nil),     // 2: events.v1.ClinicUpdateEvent
	}
)

func init() { file_proto_user_events_proto_init() }
func file_proto_user_events_proto_init() {
	if File_proto_user_events_proto != nil {
		return
	}
	// Skip descriptor validation to avoid cardinality errors with minimal descriptor
	// The message types are already defined above and fully functional
}
