// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: user_events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User registration event message
type UserRegistrationEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique user identifier
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// User email address
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// User role (PATIENT, DOCTOR, PHARMACIST, etc.)
	Role string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	// Optional user first name
	FirstName string `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Optional user last name
	LastName string `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Event timestamp (Unix timestamp in seconds)
	Timestamp int64 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// user phone number
	PhoneNumber string `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// Event type identifier
	EventType string `protobuf:"bytes,8,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Optional clinic information (for CLINIC_ADMIN users)
	ClinicData    *ClinicData `protobuf:"bytes,9,opt,name=clinic_data,json=clinicData,proto3" json:"clinic_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegistrationEvent) Reset() {
	*x = UserRegistrationEvent{}
	mi := &file_user_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegistrationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegistrationEvent) ProtoMessage() {}

func (x *UserRegistrationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_user_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegistrationEvent.ProtoReflect.Descriptor instead.
func (*UserRegistrationEvent) Descriptor() ([]byte, []int) {
	return file_user_events_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegistrationEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRegistrationEvent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRegistrationEvent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserRegistrationEvent) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserRegistrationEvent) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserRegistrationEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *UserRegistrationEvent) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserRegistrationEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *UserRegistrationEvent) GetClinicData() *ClinicData {
	if x != nil {
		return x.ClinicData
	}
	return nil
}

// Clinic data for clinic admin registration
type ClinicData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Clinic ID from profile service (for updates)
	ClinicId int64 `protobuf:"varint,1,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	// Clinic name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Physical address
	PhysicalAddress string `protobuf:"bytes,3,opt,name=physical_address,json=physicalAddress,proto3" json:"physical_address,omitempty"`
	// Contact phone
	ContactPhone string `protobuf:"bytes,4,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	// Operating hours
	OperatingHours string `protobuf:"bytes,5,opt,name=operating_hours,json=operatingHours,proto3" json:"operating_hours,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClinicData) Reset() {
	*x = ClinicData{}
	mi := &file_user_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClinicData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClinicData) ProtoMessage() {}

func (x *ClinicData) ProtoReflect() protoreflect.Message {
	mi := &file_user_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClinicData.ProtoReflect.Descriptor instead.
func (*ClinicData) Descriptor() ([]byte, []int) {
	return file_user_events_proto_rawDescGZIP(), []int{1}
}

func (x *ClinicData) GetClinicId() int64 {
	if x != nil {
		return x.ClinicId
	}
	return 0
}

func (x *ClinicData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClinicData) GetPhysicalAddress() string {
	if x != nil {
		return x.PhysicalAddress
	}
	return ""
}

func (x *ClinicData) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *ClinicData) GetOperatingHours() string {
	if x != nil {
		return x.OperatingHours
	}
	return ""
}

// Clinic update event message
type ClinicUpdateEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Profile service clinic ID
	ClinicId int64 `protobuf:"varint,1,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	// Updated clinic name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Updated physical address
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// Updated contact phone
	ContactPhone string `protobuf:"bytes,4,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	// Updated operating hours
	OperatingHours string `protobuf:"bytes,5,opt,name=operating_hours,json=operatingHours,proto3" json:"operating_hours,omitempty"`
	// Whether the clinic is active
	IsActive bool `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// Event timestamp
	Timestamp int64 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Event type identifier
	EventType     string `protobuf:"bytes,8,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClinicUpdateEvent) Reset() {
	*x = ClinicUpdateEvent{}
	mi := &file_user_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClinicUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClinicUpdateEvent) ProtoMessage() {}

func (x *ClinicUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_user_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClinicUpdateEvent.ProtoReflect.Descriptor instead.
func (*ClinicUpdateEvent) Descriptor() ([]byte, []int) {
	return file_user_events_proto_rawDescGZIP(), []int{2}
}

func (x *ClinicUpdateEvent) GetClinicId() int64 {
	if x != nil {
		return x.ClinicId
	}
	return 0
}

func (x *ClinicUpdateEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClinicUpdateEvent) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClinicUpdateEvent) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *ClinicUpdateEvent) GetOperatingHours() string {
	if x != nil {
		return x.OperatingHours
	}
	return ""
}

func (x *ClinicUpdateEvent) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ClinicUpdateEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClinicUpdateEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

// Response message for user registration events
type UserRegistrationEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the event was processed successfully
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Optional message with details
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Error code if processing failed
	ErrorCode     string `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegistrationEventResponse) Reset() {
	*x = UserRegistrationEventResponse{}
	mi := &file_user_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegistrationEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegistrationEventResponse) ProtoMessage() {}

func (x *UserRegistrationEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegistrationEventResponse.ProtoReflect.Descriptor instead.
func (*UserRegistrationEventResponse) Descriptor() ([]byte, []int) {
	return file_user_events_proto_rawDescGZIP(), []int{3}
}

func (x *UserRegistrationEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserRegistrationEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserRegistrationEventResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

// Prescription dispensed event message
type PrescriptionDispensedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prescription ID that was dispensed
	PrescriptionId string `protobuf:"bytes,1,opt,name=prescription_id,json=prescriptionId,proto3" json:"prescription_id,omitempty"`
	// Clinic ID where dispensing occurred
	ClinicId string `protobuf:"bytes,2,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	// Catalog item ID that was dispensed
	CatalogItemId string `protobuf:"bytes,3,opt,name=catalog_item_id,json=catalogItemId,proto3" json:"catalog_item_id,omitempty"`
	// Quantity dispensed
	QuantityDispensed int32 `protobuf:"varint,4,opt,name=quantity_dispensed,json=quantityDispensed,proto3" json:"quantity_dispensed,omitempty"`
	// Total cost of dispensing
	TotalCost string `protobuf:"bytes,5,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	// Event timestamp (Unix timestamp in seconds)
	Timestamp int64 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Event type identifier
	EventType     string `protobuf:"bytes,7,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrescriptionDispensedEvent) Reset() {
	*x = PrescriptionDispensedEvent{}
	mi := &file_user_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrescriptionDispensedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrescriptionDispensedEvent) ProtoMessage() {}

func (x *PrescriptionDispensedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_user_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrescriptionDispensedEvent.ProtoReflect.Descriptor instead.
func (*PrescriptionDispensedEvent) Descriptor() ([]byte, []int) {
	return file_user_events_proto_rawDescGZIP(), []int{4}
}

func (x *PrescriptionDispensedEvent) GetPrescriptionId() string {
	if x != nil {
		return x.PrescriptionId
	}
	return ""
}

func (x *PrescriptionDispensedEvent) GetClinicId() string {
	if x != nil {
		return x.ClinicId
	}
	return ""
}

func (x *PrescriptionDispensedEvent) GetCatalogItemId() string {
	if x != nil {
		return x.CatalogItemId
	}
	return ""
}

func (x *PrescriptionDispensedEvent) GetQuantityDispensed() int32 {
	if x != nil {
		return x.QuantityDispensed
	}
	return 0
}

func (x *PrescriptionDispensedEvent) GetTotalCost() string {
	if x != nil {
		return x.TotalCost
	}
	return ""
}

func (x *PrescriptionDispensedEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PrescriptionDispensedEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

var File_user_events_proto protoreflect.FileDescriptor

const file_user_events_proto_rawDesc = "" +
	"\n" +
	"\x11user_events.proto\x12\tevents.v1\"\xae\x02\n" +
	"\x15UserRegistrationEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12!\n" +
	"\fphone_number\x18\a \x01(\tR\vphoneNumber\x12\x1d\n" +
	"\n" +
	"event_type\x18\b \x01(\tR\teventType\x126\n" +
	"\vclinic_data\x18\t \x01(\v2\x15.events.v1.ClinicDataR\n" +
	"clinicData\"\xb6\x01\n" +
	"\n" +
	"ClinicData\x12\x1b\n" +
	"\tclinic_id\x18\x01 \x01(\x03R\bclinicId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x10physical_address\x18\x03 \x01(\tR\x0fphysicalAddress\x12#\n" +
	"\rcontact_phone\x18\x04 \x01(\tR\fcontactPhone\x12'\n" +
	"\x0foperating_hours\x18\x05 \x01(\tR\x0eoperatingHours\"\x86\x02\n" +
	"\x11ClinicUpdateEvent\x12\x1b\n" +
	"\tclinic_id\x18\x01 \x01(\x03R\bclinicId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12#\n" +
	"\rcontact_phone\x18\x04 \x01(\tR\fcontactPhone\x12'\n" +
	"\x0foperating_hours\x18\x05 \x01(\tR\x0eoperatingHours\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\b \x01(\tR\teventType\"r\n" +
	"\x1dUserRegistrationEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\"\x95\x02\n" +
	"\x1aPrescriptionDispensedEvent\x12'\n" +
	"\x0fprescription_id\x18\x01 \x01(\tR\x0eprescriptionId\x12\x1b\n" +
	"\tclinic_id\x18\x02 \x01(\tR\bclinicId\x12&\n" +
	"\x0fcatalog_item_id\x18\x03 \x01(\tR\rcatalogItemId\x12-\n" +
	"\x12quantity_dispensed\x18\x04 \x01(\x05R\x11quantityDispensed\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x05 \x01(\tR\ttotalCost\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\a \x01(\tR\teventTypeB\x1dZ\x1bauth-service/internal/protob\x06proto3"

var (
	file_user_events_proto_rawDescOnce sync.Once
	file_user_events_proto_rawDescData []byte
)

func file_user_events_proto_rawDescGZIP() []byte {
	file_user_events_proto_rawDescOnce.Do(func() {
		file_user_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_events_proto_rawDesc), len(file_user_events_proto_rawDesc)))
	})
	return file_user_events_proto_rawDescData
}

var file_user_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_events_proto_goTypes = []any{
	(*UserRegistrationEvent)(nil),         // 0: events.v1.UserRegistrationEvent
	(*ClinicData)(nil),                    // 1: events.v1.ClinicData
	(*ClinicUpdateEvent)(nil),             // 2: events.v1.ClinicUpdateEvent
	(*UserRegistrationEventResponse)(nil), // 3: events.v1.UserRegistrationEventResponse
	(*PrescriptionDispensedEvent)(nil),    // 4: events.v1.PrescriptionDispensedEvent
}
var file_user_events_proto_depIdxs = []int32{
	1, // 0: events.v1.UserRegistrationEvent.clinic_data:type_name -> events.v1.ClinicData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_events_proto_init() }
func file_user_events_proto_init() {
	if File_user_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_events_proto_rawDesc), len(file_user_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_events_proto_goTypes,
		DependencyIndexes: file_user_events_proto_depIdxs,
		MessageInfos:      file_user_events_proto_msgTypes,
	}.Build()
	File_user_events_proto = out.File
	file_user_events_proto_goTypes = nil
	file_user_events_proto_depIdxs = nil
}
