-- Inventory Service Database Schema
-- PostgreSQL DDL Script
-- Note: This is auto-generated by Hibernate with ddl-auto=update
-- Run this manually if you want explicit schema creation

-- Create Database
CREATE DATABASE IF NOT EXISTS inventorydb;

-- Switch to database context (in psql: \c inventorydb)

-- Create ENUM Types
CREATE TYPE unit_type_enum AS ENUM ('TABLET', 'BOTTLE', 'STRIP');
CREATE TYPE transaction_type_enum AS ENUM ('STOCK_IN', 'DISPENSED', 'EXPIRED');

-- Create CatalogItem Table
CREATE TABLE IF NOT EXISTS catalog_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    clinic_id BIGINT NOT NULL,
    drug_name VARCHAR(255) NOT NULL,
    generic_name VARCHAR(255) NOT NULL,
    unit_type unit_type_enum NOT NULL,
    reorder_level INTEGER NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_clinic_drug_name UNIQUE (clinic_id, drug_name)
);

-- Create InventoryBatch Table
CREATE TABLE IF NOT EXISTS inventory_batches (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    catalog_item_id UUID NOT NULL,
    batch_number VARCHAR(255) NOT NULL UNIQUE,
    expiry_date DATE NOT NULL,
    cost_price NUMERIC(10, 2) NOT NULL,
    available_quantity INTEGER NOT NULL CHECK (available_quantity >= 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (catalog_item_id) REFERENCES catalog_items(id) ON DELETE CASCADE,
    CONSTRAINT chk_positive_quantity CHECK (available_quantity >= 0)
);

-- Create StockTransaction Table
CREATE TABLE IF NOT EXISTS stock_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    catalog_item_id UUID NOT NULL,
    type transaction_type_enum NOT NULL,
    quantity INTEGER NOT NULL,
    reference_id VARCHAR(255),
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (catalog_item_id) REFERENCES catalog_items(id) ON DELETE CASCADE,
    CONSTRAINT chk_positive_tx_quantity CHECK (quantity > 0)
);

-- Create Indexes for Performance
CREATE INDEX idx_catalog_items_clinic_id ON catalog_items(clinic_id);
CREATE INDEX idx_catalog_items_is_active ON catalog_items(is_active);
CREATE INDEX idx_inventory_batches_catalog_item_id ON inventory_batches(catalog_item_id);
CREATE INDEX idx_inventory_batches_expiry_date ON inventory_batches(expiry_date);
CREATE INDEX idx_inventory_batches_available_qty ON inventory_batches(available_quantity);
CREATE INDEX idx_stock_transactions_catalog_item_id ON stock_transactions(catalog_item_id);
CREATE INDEX idx_stock_transactions_type ON stock_transactions(type);
CREATE INDEX idx_stock_transactions_reference_id ON stock_transactions(reference_id);
CREATE INDEX idx_stock_transactions_timestamp ON stock_transactions(timestamp);

-- Insert Sample Data (Optional)
-- Uncomment to insert test data

-- INSERT INTO catalog_items (clinic_id, drug_name, generic_name, unit_type, reorder_level, is_active)
-- VALUES 
--   (1, 'Amoxicillin 500mg', 'Amoxicillin', 'TABLET', 100, true),
--   (1, 'Ibuprofen 200mg', 'Ibuprofen', 'TABLET', 150, true),
--   (1, 'Paracetamol Syrup', 'Paracetamol', 'BOTTLE', 50, true);

-- INSERT INTO inventory_batches (catalog_item_id, batch_number, expiry_date, cost_price, available_quantity)
-- SELECT id, 'BATCH-2025-001', '2027-12-31', 5.50, 500 FROM catalog_items WHERE drug_name = 'Amoxicillin 500mg'
-- UNION ALL
-- SELECT id, 'BATCH-2025-002', '2026-06-30', 2.00, 1000 FROM catalog_items WHERE drug_name = 'Ibuprofen 200mg'
-- UNION ALL
-- SELECT id, 'BATCH-2025-003', '2026-12-31', 8.75, 200 FROM catalog_items WHERE drug_name = 'Paracetamol Syrup';
